---
title: "CGM measurements of a health 30-something male"
author: "Márton Kiss, MD"
format:
  docx:
    fig-width: 6
    fig-height: 4
    reference-doc: custom_ref_doc.docx
  html: default
editor: visual
prefer-html: true
toc: true
toc-depth: 2
execute:
  echo: true
  warning: false
---

```{r setup}


source( here::here( "Inst", "article", "functions", "load_stuff.r"))

# source_all_files(here::here("inst","example_quarto","backend")) # Run slow stuff; 
##recommend running separately

load_all_Rdata(directory=here::here("Inst","article","backend")) # Load slow suff's output

source( here::here( "Inst", "article", "functions", "wrangling.r"))

```

```{r, child = here::here("Inst", "article", "child1_preamble.qmd")}
```

\newpage

```{r, child = here::here("Inst", "article", "child2.qmd")}
```

\newpage

```{r, child = here::here("Inst", "article", "child3.qmd")}
```

\newpage

# Remarks

<!-- ### MD5 checksum of the database used -->

```{r, comment='', results='asis'}
#tools::md5sum(fil) # %>% as.character # Uncomment reporting path is not desirable
```

### Other information regarding the document's compilation

```{r, comment='', results='asis'}
sessionInfo() %>% report::report() %>% cat()
```

### Time of compilation

```{r last_chunk, results='asis'}
Sys.time() %>% as.character %>% cat
save.image(file = here::here("Inst","article","end_state.rdata"))
```
